# Generated by Django 5.1.6 on 2026-03-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unique', models.CharField(max_length=50, unique=True, verbose_name="N° Unique d'identification")),
                ('code_etablissement', models.CharField(max_length=20, verbose_name='Code établissement')),
                ('numero_site', models.CharField(blank=True, max_length=20, verbose_name='N° Site')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('age', models.PositiveIntegerField(verbose_name='Âge')),
                ('age_en_mois', models.BooleanField(default=False, verbose_name='Âge en mois (< 2 ans)')),
                ('type_client', models.CharField(choices=[('1', 'Client sous TARV'), ('2', 'Enfant exposé'), ('3', 'Femme enceinte'), ('4', 'Femme allaitante'), ('5', 'Population clés')], max_length=1, verbose_name='Type de client')),
                ('population_cles', models.CharField(blank=True, choices=[('TS', 'Travailleur(se) de sexe'), ('HSH', 'Hommes ayant des rapports sexuels avec hommes'), ('UD', 'Usagers de drogues'), ('PC', 'Populations Carcérales')], max_length=10, verbose_name='Population clés')),
                ('date_mise_sous_arv', models.DateField(verbose_name='Date de mise sous ARV')),
                ('contact_telephone', models.CharField(max_length=20, verbose_name='Contact téléphonique')),
                ('residence_adresse', models.CharField(max_length=255, verbose_name='Résidence/Adresse géographique')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.PositiveIntegerField(verbose_name="N° d'ordre (Colonne A)")),
                ('date_rdv', models.DateField(verbose_name='Date du RDV')),
                ('date_derniere_visite', models.DateField(verbose_name='Date de la dernière visite')),
                ('motif_rdv', models.CharField(choices=[('1', 'Bilan initial'), ('2', 'Bilan de suivi'), ('3', 'Charge virale'), ('4', 'Renouvellement ordonnance'), ('5', 'Visite de suivi'), ('6', 'PCR'), ('7', 'Statut définitif enfant exposé'), ('8', 'CO/ETP'), ('9', 'Autre')], max_length=1, verbose_name='Motif du RDV')),
                ('motif_rdv_autre', models.CharField(blank=True, max_length=200, verbose_name='Motif autre (préciser)')),
                ('date_relance_preventive', models.DateField(blank=True, null=True, verbose_name='Date relance préventive (J-2)')),
                ('moyen_relance_preventive', models.CharField(blank=True, choices=[('1', 'Appel téléphonique'), ('2', 'VAD'), ('3', 'SMS'), ('4', 'Autre')], max_length=1, verbose_name='Moyen relance préventive')),
                ('resultat_relance_preventive', models.CharField(blank=True, choices=[('1', 'RDV confirmé'), ('2', 'Injoignable'), ('3', 'RDV reprogrammé (préciser la date)'), ('4', 'Refus du RDV'), ('5', 'Client décédé'), ('6', 'Pas de réponse au SMS'), ('7', 'Suivi dans un autre centre'), ('8', 'Ne répond pas aux appels'), ('9', 'Pas de relance effectuée'), ('10', 'Autre')], max_length=2, verbose_name='Résultat relance préventive')),
                ('date_relance_absence', models.DateField(blank=True, null=True, verbose_name='Date relance absence (J+7)')),
                ('moyen_relance_absence', models.CharField(blank=True, choices=[('1', 'Appel téléphonique'), ('2', 'VAD'), ('3', 'SMS'), ('4', 'Autre')], max_length=1, verbose_name='Moyen relance absence')),
                ('resultat_relance_absence', models.CharField(blank=True, choices=[('1', 'RDV confirmé'), ('2', 'Injoignable'), ('3', 'RDV reprogrammé (préciser la date)'), ('4', 'Refus du RDV'), ('5', 'Client décédé'), ('6', 'Pas de réponse au SMS'), ('7', 'Suivi dans un autre centre'), ('8', 'Ne répond pas aux appels'), ('9', 'Pas de relance effectuée'), ('10', 'Autre')], max_length=2, verbose_name='Résultat relance absence')),
                ('date_rdv_reprogramme', models.DateField(blank=True, null=True, verbose_name='Date RDV reprogrammé')),
                ('est_venu', models.BooleanField(null=True, verbose_name='Patient venu au RDV')),
                ('date_prochain_rdv', models.DateField(blank=True, null=True, verbose_name='Date prochain RDV')),
                ('motif_non_venue', models.CharField(blank=True, max_length=200, verbose_name='Motif de non-venue')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_crees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='agenda.patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_rdv', 'numero_ordre'],
            },
        ),
    ]
