# Generated by Django 5.1.6 on 2026-04-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='motif_prochain_rdv',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motif du prochain RDV'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='motif_rdv',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
