# Generated by Django 5.1.6 on 2026-03-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheseHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debut', models.DateField(verbose_name='Début de semaine')),
                ('semaine_fin', models.DateField(verbose_name='Fin de semaine')),
                ('total_rdv_prevus', models.PositiveIntegerField(default=0)),
                ('total_venus', models.PositiveIntegerField(default=0)),
                ('total_absents', models.PositiveIntegerField(default=0)),
                ('total_relances', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Synthèse Hebdomadaire',
                'ordering': ['-semaine_debut'],
                'unique_together': {('semaine_debut', 'semaine_fin')},
            },
        ),
        migrations.CreateModel(
            name='SyntheseMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('total_rdv_prevus', models.PositiveIntegerField(default=0)),
                ('total_venus', models.PositiveIntegerField(default=0)),
                ('total_absents', models.PositiveIntegerField(default=0)),
                ('total_perdus_de_vue', models.PositiveIntegerField(default=0, verbose_name='Perdus de vue')),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Synthèse Mensuelle',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('mois', 'annee')},
            },
        ),
    ]
